### ISSUE TITLE
Add Initial Content

### ISSUE THREAD

**Issue by J1A2D3** [csctd/profile-website-J1A2D3#4]
- [ ] A contact button (email, other social)
- [ ] An about me page 
- [ ] Experience (resume)
- [ ] portfolio (links)

**Comment by J1A2D3** [comment]
![unnamed](https://github.com/csctd/profile-website-J1A2D3/assets/78859395/0c35a00f-03a5-416c-b2df-3cce4281f3d7)

**Comment by sarmenti7** [comment]
Nice work! Can you combine some of these pages together to simplify your navigation menu?
